### PR TITLE
support version 2, 3, 4 of the logger_entry ABI

### PR DESCRIPTION
**Pull request by syncxplus**

### CODE REVIEW

**Comment by sorccu** [comment]
Thanks for the PR. Maybe I'm just not seeing it, but looking at the changes it doesn't really look like this changes the current behavior at all... Setting the cursor to the header length should ensure that it always skips the right amount of bytes. Could you provide a simple test case that fails on the current `master` branch but works with your modified branch?

**Comment by syncxplus** [comment]
Hey there,

Actually, it is not the problem of version 2,3,4, but the problem of version 1. Here is the issue:

headerSize = @buffer.readUInt16LE(cursor) or HEADER_SIZE_V1

As we known, in the logger_entry version 1, there is no header size but only padding content in the struct. If all the padding are zero, the code works well. However, in some case, I found the padding content are random values. That will break the parser and the output is meaningless characters.

/\* \* The userspace structure for version 1 of the logger_entry ABI. \* This structure is returned to userspace by the kernel logger \* driver unless an upgrade to a newer ABI version is requested. _/struct logger_entry {    uint16_t    len;    /_ length of the payload _/    uint16_t    __pad;  /_ no matter what, we get 2 bytes of padding _/ The padding are random value in some devices    int32_t     pid;    /_ generating process's pid _/    int32_t     tid;    /_ generating process's tid _/    int32_t     sec;    /_ seconds since Epoch _/    int32_t     nsec;   /_ nanoseconds _/    char        msg[0]; /_ the entry's payload */} **attribute**((**packed**));

Unfortunately, it only happened on certain devices. If you don’t have one of them, you may not see the failure case. For example, you can try the nubia Z9 mini.

If you need any logs for analyze, I can help you get it.
Date: Wed, 6 Jan 2016 10:21:29 -0800

**Comment by sorccu** [comment]
Right, now I remember thinking about the same thing a long time ago. There's a potential problem with this patch, though. If the padding truly is fully random, it's possible that it may sometimes have the value 24 or 28. Then we'd skip too many bytes and corrupt the rest of the stream. To reduce the likelihood of that happening, we may have to set the header size when we read the first entry, and keep using the same value after that. Then we'd have a 2/65535 chance of being wrong and corrupting the stream, for the entire duration of the stream.

**Comment by sorccu** [comment]
If possible, I would like you to collect a very large binary log from your Nubia Z9 Mini. Then we can check what the random values usually are. You don't have to give the full log, just the list of unique random values.

**Comment by syncxplus** [comment]
Yes, it is a risk for the random value maybe equal to 24 or 28.

I see the typical value is 2xxxx and I didn’t know why it was that. Anyway, it was not always happened. In fact, I also tried another model of nubia device, it seems not happened.

Here I print the header size in lib/logcat/parser/binary.js
headerSize = this.buffer.readUInt16LE(cursor) || HEADER_SIZE_V1;
console.log('headerSize: ' + headerSize)
/usr/local/bin/node logcat-debug.js
var logcat = require('../lib/logcat');
var spawn = require('child_process').spawn;
// Retrieve a binary log stream
var proc = spawn('adb', ['logcat', '-B']);
// Connect logcat to the stream
reader = logcat.readStream(proc.stdout);
reader.on('entry', function(entry) {
  //console.log(entry.message);
});
// Make sure we don't leave anything hanging
process.on('exit', function() {
  proc.kill();
});
The output trace:
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261
headerSize: 28261

**Comment by syncxplus** [comment]
I did more test today and I found the patch couldn't solve the nubia Z9 mini problem. So I will close the PR.
The behavior of this device is wired. If I found more I will let you know.

**Comment by sorccu** [comment]
Sometimes the binary log can get corrupted by itself. I've only seen it happen once or twice. But try to clear the entire log with `adb logcat -c` to make sure that isn't the issue.

**Pull request closed without merging**
